### ISSUE TITLE
1st Meetup Todo

### ISSUE THREAD

**Issue by michaelcullum** [phpsurrey/phpsurrey.uk#8]
- [x] Organise speaker
- [x] Book venue
- [x] Get speaker abstract
- [x] Put on website
- [x] Eventbrite
- [ ] Meetup.com
- [x] Announce on twitter
- [ ] Announce it on mailing list

**Comment by MikeRogers0** [comment]
Eventbrite and Meetup?

**Comment by michaelcullum** [comment]
Yeah. Meetup will be more of a marketing thing, eventbrite is for actual registration. One of the problems with meetup is there is no way to get a list of member email addresses.
